### ISSUE TITLE
mkdir: can't create directory '/github/home/.aws': File exists

### ISSUE THREAD

**Issue by maximilianobaez** [MGenteluci/cloudformation-deploy-action#10]
I added your action to my CI with the command:

```
- name: Deploy to AWS via CloudFormation
        uses: mgenteluci/cloudformation-deploy-action@v1.4.1
        env:
          TEMPLATE: ${{ env.AWS_TEMPLATE_FILE_DEV }}
          AWS_STACK_NAME: ${{ env.AWS_STACK_NAME }}
          AWS_REGION: ${{ env.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEPLOY_BUCKET: ${{ env.AWS_S3_BUCKET }}
```
I get the error when after the first execution: mkdir: can't create directory '/github/home/.aws': File exists

This is the complete error:

```
runner/_work/_temp/_runner_file_commands":"/github/file_commands" -v "/opt/devops/actions-runner/_work/lambda-test/lambda-test":"/github/workspace" 35b096:080abb3e763f4f4c8170952287575800
mkdir: cannot create directory '/github/home/.aws': File exists
```
