### ISSUE TITLE
Could it support 2 deployments? 

### ISSUE THREAD

**Issue by CarlosMenaPhotoslurp** [MGenteluci/cloudformation-deploy-action#5]
I found an issue when I try to deploy two stacks in the same workflow (github action):
`mkdir: cannot create directory '/github/home/.aws': File exists`
  ```
 -
      name: "Deploy analytics celery stack"
      uses: mgenteluci/cloudformation-deploy-action@v1.4.0
      env:
        TEMPLATE: 'amazon-aws/cloudformation/prod-ecs-celery-analytics.yml'
        AWS_STACK_NAME: 'prod-ecs-celery-analytics'
        AWS_REGION: 'eu-west-1'
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_DEPLOY_BUCKET: ${{secrets.AWS_CLOUDFORMATION_BUCKET}}
    -
      name: "Deploy async celery stack"
      uses: mgenteluci/cloudformation-deploy-action@v1.4.0
      env:
        TEMPLATE: 'amazon-aws/cloudformation/prod-ecs-celery-async.yml'
        AWS_STACK_NAME: 'prod-ecs-celery-async'
        AWS_REGION: 'eu-west-1'
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_DEPLOY_BUCKET: ${{secrets.AWS_CLOUDFORMATION_BUCKET}}
```
